#include "ExpoGaodeMapTurboModuleSpec.h"

using namespace rnoh;

NativeExpoGaodeMapTurboModuleSpecJSI::NativeExpoGaodeMapTurboModuleSpecJSI(
    const ArkTSTurboModule::Context ctx,
    const std::string name)
    : ArkTSTurboModule(ctx, name) {
  methodMap_ = {
      ARK_METHOD_METADATA(setPrivacyShow, 2),
      ARK_METHOD_METADATA(setPrivacyAgree, 1),
      ARK_METHOD_METADATA(setPrivacyVersion, 1),
      ARK_METHOD_METADATA(resetPrivacyConsent, 0),
      ARK_METHOD_METADATA(getPrivacyStatus, 0),
      ARK_METHOD_METADATA(initSDK, 1),
      ARK_METHOD_METADATA(isNativeSDKConfigured, 0),
      ARK_METHOD_METADATA(setLoadWorldVectorMap, 1),
      ARK_METHOD_METADATA(getVersion, 0),
      ARK_METHOD_METADATA(start, 0),
      ARK_METHOD_METADATA(stop, 0),
      ARK_METHOD_METADATA(isStarted, 0),
      ARK_METHOD_METADATA(startUpdatingHeading, 0),
      ARK_METHOD_METADATA(stopUpdatingHeading, 0),
      ARK_ASYNC_METHOD_METADATA(getCurrentLocation, 0),
      ARK_ASYNC_METHOD_METADATA(coordinateConvert, 2),
      ARK_METHOD_METADATA(setLocatingWithReGeocode, 1),
      ARK_METHOD_METADATA(setInterval, 1),
      ARK_METHOD_METADATA(setDistanceFilter, 1),
      ARK_METHOD_METADATA(setDesiredAccuracy, 1),
      ARK_METHOD_METADATA(setLocationMode, 1),
      ARK_METHOD_METADATA(setLocationTimeout, 1),
      ARK_METHOD_METADATA(setReGeocodeTimeout, 1),
      ARK_METHOD_METADATA(setGeoLanguage, 1),
      ARK_METHOD_METADATA(setAllowsBackgroundLocationUpdates, 1),
      ARK_METHOD_METADATA(setLocationProtocol, 1),
      ARK_METHOD_METADATA(setOnceLocation, 1),
      ARK_METHOD_METADATA(setSensorEnable, 1),
      ARK_METHOD_METADATA(setWifiScan, 1),
      ARK_METHOD_METADATA(setGpsFirst, 1),
      ARK_METHOD_METADATA(setOnceLocationLatest, 1),
      ARK_METHOD_METADATA(setLocationCacheEnable, 1),
      ARK_METHOD_METADATA(setHttpTimeOut, 1),
      ARK_METHOD_METADATA(setPausesLocationUpdatesAutomatically, 1),
      ARK_METHOD_METADATA(addListener, 1),
      ARK_METHOD_METADATA(removeListeners, 1),
      ARK_ASYNC_METHOD_METADATA(checkLocationPermission, 0),
      ARK_ASYNC_METHOD_METADATA(requestLocationPermission, 0),
      ARK_ASYNC_METHOD_METADATA(requestBackgroundLocationPermission, 0),
      ARK_METHOD_METADATA(distanceBetweenCoordinates, 2),
      ARK_METHOD_METADATA(isPointInCircle, 3),
      ARK_METHOD_METADATA(isPointInPolygon, 2),
      ARK_METHOD_METADATA(calculatePolygonArea, 1),
      ARK_METHOD_METADATA(calculateRectangleArea, 2),
      ARK_METHOD_METADATA(getNearestPointOnPath, 2),
      ARK_METHOD_METADATA(calculateCentroid, 1),
      ARK_METHOD_METADATA(calculatePathBounds, 1),
      ARK_METHOD_METADATA(encodeGeoHash, 2),
      ARK_METHOD_METADATA(simplifyPolyline, 2),
      ARK_METHOD_METADATA(calculatePathLength, 1),
      ARK_METHOD_METADATA(parsePolyline, 1),
      ARK_METHOD_METADATA(getPointAtDistance, 2),
      ARK_METHOD_METADATA(latLngToTile, 2),
      ARK_METHOD_METADATA(tileToLatLng, 1),
      ARK_METHOD_METADATA(latLngToPixel, 2),
      ARK_METHOD_METADATA(pixelToLatLng, 2),
      ARK_METHOD_METADATA(findPointInPolygons, 2),
      ARK_METHOD_METADATA(generateHeatmapGrid, 2),
      ARK_METHOD_METADATA(openAppSettings, 0),
  };
}
